#!/bin/bash

directory="/home/aiden/Téléchargements" # Chemin d'accès du dossier où se trouve les téléchargements
status_vert="/home/aiden/Documents/Tools/My_Tool/MajDiscord/src/image/icone-d-information-vert.png"
status_rouge="/home/aiden/Documents/Tools/My_Tool/MajDiscord/src/image/icone-d-information-rouge.png"

#notify-send "Maj Discord" "PID du script : $$" # Notifications indicant le PID du script

inotifywait -m -e create --format "%f" "$directory" | while read new_file # Si un fichier se crée dans le répertoire $directory cela déclange la suite du programme
do
    if [[ "$new_file" =~ ^discord.*\.deb$ ]]; then # Vérifie si c'est un ficher du type discord*.deb
        inotifywait -q -e close_write "$directory/$new_file" # Atend que le ficher soit ne soit plus entraint d'être écris (téléchargement fini)

        notify-send "Maj Discord" "Mise à jour en cours..." # Notification du début de la mise à jour
        sudo /usr/bin/dpkg -i "$directory"/"$new_file" > /dev/null 2>&1 # Installe la mise à jour

        if [ $? -eq 0 ]; then # Si la mise à jour à marché, notification Mise à jour réussi, sinon Mise à jour échoué
            notify-send --urgency=critical -i $status_vert "Maj Discord" "Mise à jour réussie"
        else
            notify-send --urgency=critical -i $status_rouge "Maj Discord" "Mise à jour échouée"
        fi
        rm "$directory/$new_file" > /dev/null 2>&1 # Suppression du fichier discord*.deb
        sleep 1
    fi
done
